import {
	PUBLIC_PROVIDER,
	PUBLIC_GLOBAL_ANONYMOUS_FEED_ADDRESS,
	PUBLIC_ADAPTER,
	PUBLIC_RELAYER_URL,
  PUBLIC_IPFS_AUTH,
  PUBLIC_IPFS_GATEWAY,
  PUBLIC_IPFS_HOST,
  PUBLIC_FIREBASE_PROJECT_ID,
  PUBLIC_FIREBASE_API_KEY,
  PUBLIC_FIREBASE_DOMAIN,
  PUBLIC_FIREBASE_STORAGE_BUCKET,
  PUBLIC_FIREBASE_APP_ID,
  PUBLIC_FIREBASE_MSG_SENDER_ID

} from '$env/static/public'

export const GLOBAL_ANONYMOUS_FEED_ADDRESS = PUBLIC_GLOBAL_ANONYMOUS_FEED_ADDRESS
export const PROVIDER = PUBLIC_PROVIDER
export const RELAYER_URL = PUBLIC_RELAYER_URL
export const ADAPTER = PUBLIC_ADAPTER

// FIXME: Find a way to make sure those values don't leak
export const IPFS_AUTH= PUBLIC_IPFS_AUTH
export const IPFS_GATEWAY = PUBLIC_IPFS_GATEWAY
export const IPFS_HOST = PUBLIC_IPFS_HOST

// FIXME: Find a way to make sure those values don't leak
export const FIREBASE_PROJECT_ID = PUBLIC_FIREBASE_PROJECT_ID
export const FIREBASE_API_KEY = PUBLIC_FIREBASE_API_KEY
export const FIREBASE_DOMAIN = PUBLIC_FIREBASE_DOMAIN
export const FIREBASE_STORAGE_BUCKET = PUBLIC_FIREBASE_STORAGE_BUCKET
export const FIREBASE_APP_ID = PUBLIC_FIREBASE_APP_ID
export const FIREBASE_MSG_SENDER_ID = PUBLIC_FIREBASE_MSG_SENDER_ID


export const CREATE_PERSONA_GO_PRICE = 10
export const NEW_POST_REP_PRICE = 5
export const NEW_POST_GO_PRICE = 5
export const NEW_POST_REP_WIN = 5
export const NEW_POST_REP_LOSS = 5
export const VOTE_GO_PRICE = 1
export const VOTE_REP_WIN = 1
export const DEFAULT_GO_AMOUNT = 30

export const MAX_DIMENSIONS = {
	PERSONA_PICTURE: {
		width: 500,
		height: 500,
	},
	PERSONA_COVER: {
		width: 1440,
		height: 810,
	},
	POST_PICTURE: {
		width: 900,
		height: 900,
	},
}
